# Generated by Django 3.0.5 on 2020-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200501_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='authors',
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(max_length=50),
        ),
    ]
